server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    redis:
      repository-type: default
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework.security: TRACE

cipher:
  AES:
    key: "1234567812345678"
    iv : "1234567812345678"
    algoList : "AES/CBC/PKCS5PADDING"

#server.port=8080
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:secure-bank-pro.p12
#server.ssl.key-store-password=root
#server.ssl.enabled=true
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:postgresql://postgresdb/bank
#spring.datasource.username=user
#spring.datasource.password=password
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#spring.datasource.url=jdbc:mysql://localhost:3306/bankdb
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true

#spring.session.redis.repository-type=default
#spring.data.redis.server=redis
#spring.data.redis.host=redis
#spring.data.redis.port=6379
#
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.highlight_sql=true
#
#logging.level.org.springframework.security=TRACE


#server.port=8080
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:secure-bank-pro.p12
#server.ssl.key-store-password=root
#server.ssl.enabled=true
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:postgresql://postgresdb/bank
#spring.datasource.username=user
#spring.datasource.password=password
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
##
##spring.datasource.url=jdbc:mysql://localhost:3306/bankdb
##spring.datasource.username=root
##spring.datasource.password=password
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.jpa.show-sql=true
#
#spring.session.redis.repository-type=default
#spring.data.redis.server=redis
#spring.data.redis.host=redis
#spring.data.redis.port=6379
#
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.highlight_sql=true
#
#logging.level.org.springframework.security=TRACE