server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    redis:
      repository-type: default
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework.security: TRACE

frontend:
  url: http://localhost:3000

cookie:
  domain: localhost


cipher:
  AES:
    key: "1234567812345678"
    iv : "1234567812345678"
    algoList : "AES/CBC/PKCS5PADDING"
